config/routes.rb
TonyBlog::Application.routes.draw do
  root :to => 'pages#welcome' #homepages
  get "profile" => 'pages#profile', :as => "profile"
  
#------------------------------------------------------------------------------------------------------------------------------
  
  get "class_projects" => 'class_projects#index', :as => "class_projects"
  get "class_projects/new" => 'class_projects#new', :as => "new_class_project"
  
  get "class_projects/:id" => 'class_projects#show', :as => "class_project"
  get "class_projects/:id/edit" => 'class_projects#edit', :as => "edit_class_project"
  
  post "class_projects" => 'class_projects#create' 
  put "class_projects/:id" => 'class_projects#update'
  
  delete "class_projects/:id/delete" => 'class_projects#destroy', :as => "delete_class_project"


  
#------------------------------------------------------------------------------------------------------------------------------
  
  get "contacts" => 'contacts#index', :as => "contacts"
  get "contacts/new" => 'contacts#new', :as => "new_contact"
  
  get "contacts/:id" => 'contacts#show', :as => "contact"
  get "contacts/:id/edit" => 'contacts#edit', :as => "edit_contact"
  
  post "contacts" => 'contacts#create' 
  put "contacts/:id" => 'contacts#update'
  
  delete "contacts/:id/delete" => 'contacts#destroy', :as => "delete_contact"


  
#------------------------------------------------------------------------------------------------------------------------------

  get "articles" => 'articles#index', :as => "articles"
  get "articles/new" => 'articles#new', :as => "new_article"

  get "articles/:id" => 'articles#show', :as => "article"
  get "articles/:id/edit" => 'articles#edit', :as => "edit_article"

  post "articles" => 'articles#create' 
  put "articles/:id" => 'articles#update'
  
  delete "articles/:id/delete" => 'articles#destroy', :as => "delete_article"
  post "articles/like" => 'articles#like', :as => "like_article"
  #:article_id
#------------------------------------------------------------------------------------------------------------------------------
  
  
  post "create_user" => 'users#create', :as => "create_user"
  get "signup" => 'users#new', :as => "signup"
  
  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login"
  
  get "logout" => 'logins#destroy', :as => "logout"
  
  
    
  
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :draft, :title
  has_many :likes
  
  validates :title, :presence => true
  validates :body, :presence => true
  
  scope :is_draft, where(:draft => true)
  
  # add an instance method called excerpt, which returns only the first 30 characters of the article's body.
  
  def excerpt(id)
    @article = Article.find(id)
    excpt = @article.body.slice(0..30)
    excpt
  end
  
# add an instance method called relative_length, which returns either "short", "medium", or "long" respectively if the article body's length is 50 characters, 100 characters, or 300 characters.
  def relative_length(id)
    @article = Article.find(id)
    char = @article.body.length
    
    if char <= 50
      return "short"
    elsif char > 50 && char <=100
      return "medium"
    elsif char > 100 && char <=300
      return "long"
    else
      return "not sure what is goin on!"
    end
  end
  
  def convert_to_finished
      # Notice it's "update_attribute" - not "update_attributes" (sssss).
    update_attribute(:draft, false)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  skip_before_filter :authorize, :only => [:index, :show]
  
  def index
    @articles = Article.all
  end
  
  
  def new
    @article = Article.new
  
  end
  
  def create
    @article = Article.new(params[:article])
    
    if @article.save
      redirect_to articles_path, :notice => "Saved a new article! You feel that? That's a pat on the back!"
    else
      render "new"
    end
    
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def edit
    @article = Article.find(params[:id])
    
  end
  
  def like
    # @article = Article.find(params[:id])
#     # @like = Like.new

    @article = Article.find(params[:id])
     
    Like.create({"article_id" => @article.id, "ip_address" => "tony"})
    redirect_to articles_path
    
  end
  
  def update
    @articles = Article.all
    @article = Article.find(params[:id])
    
    if @article.update_attributes(params[:article])
      redirect_to articles_path
    else
    end 
    
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    
    redirect_to articles_path
  end
    
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit <%=@article.title %></h1>

<%= form_for @article do |a| %>

  <%= a.label :title %>
  <%= a.text_field :title %>

  <%= a.label :body %>
  <%= a.text_field :body %>
	
  <%= a.label :draft %>
  <%= a.check_box :draft %>
	
  <%= a.submit %>

<% end %>

app/views/articles/index.html.erb
<h1>Articles</h1>


<%= link_to "Sign up for a new user account.", signup_path %> | <%= link_to "Log in.", login_path %>



<% @articles.each do |a|%>

	<p><%= link_to(a.title, article_path(a.id)) %></p>
<%end%>

<%= link_to("New Article", new_article_path) %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<% @article.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
<% end %>

<%= form_for @article do |a| %>

  <%= a.label :title %>
  <%= a.text_field :title %>

  <%= a.label :body %>
  <%= a.text_field :body %>
	
  <%= a.label :draft %>
  <%= a.check_box :draft %>
	
  <%= a.submit %>

<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %>'s Information</h1> 
	<p>Body: <%= @article.body %></p>
	<p>Draft? <%= @article.draft %></p>
	
	<%= button_to("Like" , like_article_path) %>
		
	
<%= link_to("Edit Article", edit_article_path) %>
<%= link_to("Delete Article", delete_article_path, :method => :delete) %>