config/routes.rb
TonyBlog::Application.routes.draw do
  root :to => 'pages#welcome' #homepages
  get "profile" => 'pages#profile', :as => "profile"
  
#------------------------------------------------------------------------------------------------------------------------------
  
  get "class_projects" => 'class_projects#index', :as => "class_projects"
  get "class_projects/new" => 'class_projects#new', :as => "new_class_project"
  
  get "class_projects/:id" => 'class_projects#show', :as => "class_project"
  get "class_projects/:id/edit" => 'class_projects#edit', :as => "edit_class_project"
  
  post "class_projects" => 'class_projects#create' 
  put "class_projects/:id" => 'class_projects#update'
  
  delete "class_projects/:id/delete" => 'class_projects#destroy', :as => "delete_class_project"


  
#------------------------------------------------------------------------------------------------------------------------------
  
  get "contacts" => 'contacts#index', :as => "contacts"
  get "contacts/new" => 'contacts#new', :as => "new_contact"
  
  get "contacts/:id" => 'contacts#show', :as => "contact"
  get "contacts/:id/edit" => 'contacts#edit', :as => "edit_contact"
  
  post "contacts" => 'contacts#create' 
  put "contacts/:id" => 'contacts#update'
  
  delete "contacts/:id/delete" => 'contacts#destroy', :as => "delete_contact"


  
#------------------------------------------------------------------------------------------------------------------------------

  get "articles" => 'articles#index', :as => "articles"
  get "articles/new" => 'articles#new', :as => "new_article"

  get "articles/:id" => 'articles#show', :as => "article"
  get "articles/:id/edit" => 'articles#edit', :as => "edit_article"

  post "articles" => 'articles#create' 
  put "articles/:id" => 'articles#update'
  
  delete "articles/:id/delete" => 'articles#destroy', :as => "delete_article"
  post "articles/like" => 'articles#like', :as => "like_article"
  #:article_id
#------------------------------------------------------------------------------------------------------------------------------
  
  
  post "create_user" => 'users#create', :as => "create_user"
  get "signup" => 'users#new', :as => "signup"
  
  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login"
  
  get "logout" => 'logins#destroy', :as => "logout"
  
  
    
  
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name
  
  validates :name, :presence => true
  validates :email, :presence => true
  validates :message, :presence => true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  skip_before_filter :authorize, :only => [:index, :show]
  
  def index
    @contacts = Contact.all
  end
  
  
  def new
    @contact = Contact.new
  
  end
  
  def create
    @contact = Contact.new(params[:contact])
    
    if @contact.save
      redirect_to contacts_path
    else
      render "new"
    end
  end
  
  def show
    @contact = Contact.find(params[:id])
  end
  
  def edit
    @contact = Contact.find(params[:id])
  end
  
  def update
    @contacts = Contact.all
    @contact = Contact.find(params[:id])
    
      if @contact.update_attributes(params[:contact])
        redirect_to contacts_path
      else
      end  
  end
  
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    
    redirect_to contacts_path
  end






end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/edit.html.erb
<h1>Edit <%=@contact.name %></h1>

<%= form_for @contact do |p| %>

  <%= p.label :name %>
  <%= p.text_field :name %>

  <%= p.label :email %>
  <%= p.text_field :email %>
	
  <%= p.label :message %>
  <%= p.text_field :message %>
	
  <%= p.submit %>

<% end %>


<!-- <p>Do you want to delete <%=@contact.name %> from your class projects? Click below</p>

<form action = "/class_projects/<%=@contact.id%>/delete" method = "post">
  <input type = "submit" value = "Delete forever!">
</form> -->

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<% @contacts.each do |c|%>

	<p><%= link_to(c.name, contact_path(c.id)) %></p>
<%end%>

<%= link_to("New Contact", new_contact_path) %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<% @contact.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
<% end %>

<%= form_for @contact do |p| %>

  <%= p.label :name %>
  <%= p.text_field :name %>

  <%= p.label :email %>
  <%= p.text_field :email %>
	
  <%= p.label :message %>
  <%= p.text_field :message %>
	
  <%= p.submit %>

<% end %>

app/views/contacts/show.html.erb
<h1><%= @contact.name %>'s Information</h1> 
	<p>E-mail: <%= @contact.email %></p>
	<p>Message: <%= @contact.message %></p>
	
<%= link_to("Edit Contact", edit_contact_path) %>
<%= link_to("Delete Contact", delete_contact_path, :method => :delete) %>