config/routes.rb
TonyBlog::Application.routes.draw do
  root :to => 'pages#welcome' #homepages
  get "profile" => 'pages#profile', :as => "profile"
  
#------------------------------------------------------------------------------------------------------------------------------
  
  get "class_projects" => 'class_projects#index', :as => "class_projects"
  get "class_projects/new" => 'class_projects#new', :as => "new_class_project"
  
  get "class_projects/:id" => 'class_projects#show', :as => "class_project"
  get "class_projects/:id/edit" => 'class_projects#edit', :as => "edit_class_project"
  
  post "class_projects" => 'class_projects#create' 
  put "class_projects/:id" => 'class_projects#update'
  
  delete "class_projects/:id/delete" => 'class_projects#destroy', :as => "delete_class_project"


  
#------------------------------------------------------------------------------------------------------------------------------
  
  get "contacts" => 'contacts#index', :as => "contacts"
  get "contacts/new" => 'contacts#new', :as => "new_contact"
  
  get "contacts/:id" => 'contacts#show', :as => "contact"
  get "contacts/:id/edit" => 'contacts#edit', :as => "edit_contact"
  
  post "contacts" => 'contacts#create' 
  put "contacts/:id" => 'contacts#update'
  
  delete "contacts/:id/delete" => 'contacts#destroy', :as => "delete_contact"


  
#------------------------------------------------------------------------------------------------------------------------------

  get "articles" => 'articles#index', :as => "articles"
  get "articles/new" => 'articles#new', :as => "new_article"

  get "articles/:id" => 'articles#show', :as => "article"
  get "articles/:id/edit" => 'articles#edit', :as => "edit_article"

  post "articles" => 'articles#create' 
  put "articles/:id" => 'articles#update'
  
  delete "articles/:id/delete" => 'articles#destroy', :as => "delete_article"
  post "articles/like" => 'articles#like', :as => "like_article"
  #:article_id
#------------------------------------------------------------------------------------------------------------------------------
  
  
  post "create_user" => 'users#create', :as => "create_user"
  get "signup" => 'users#new', :as => "signup"
  
  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login"
  
  get "logout" => 'logins#destroy', :as => "logout"
  
  
    
  
  
end

app/models/class_project.rb
class ClassProject < ActiveRecord::Base
  attr_accessible :category, :featured, :name
  
  validates :name, :presence => true
  validates :category, :presence => true
  
  scope :is_featured, where(:featured => true)
  
end

app/controllers/class_projects_controller.rb
class ClassProjectsController < ApplicationController
  
  skip_before_filter :authorize, :only => [:index, :show]
  
  def index
    @class_projects = ClassProject.all
  end
    
  def new
    @class_project = ClassProject.new
  end
  
  def create
    
    @class_project = ClassProject.new(params[:class_project])
    
    if @class_project.save
        redirect_to class_projects_path # The "index" action.
      
        # "Redirecting" means a **new request** is created. It is creating
        # a new request to the users_path.
    else
        # 1. Re-show the form.
        # 2. Display relevant errors.
      
        # Override the default view that would be loaded:
      render "new" # Refers to /app/views/users/new
    end
  end
    
  def edit
    @class_project = ClassProject.find(params[:id])
  end
  
  def update
    @class_projects = ClassProject.all
    @class_project = ClassProject.find(params[:id])
    
    if @class_project.update_attributes(params[:class_project])
      redirect_to class_projects_path
    else
    end
    
  end  
  
  def destroy
    @class_project = ClassProject.find(params[:id])
    @class_project.destroy
    
    redirect_to class_projects_path
  end
  
  def show
    @class_project = ClassProject.find(params[:id])
  end
  
  
  
end

app/helpers/class_projects_helper.rb
module ClassProjectsHelper
end

app/views/class_projects/edit.html.erb
<h1>Edit <%=@class_project.name %></h1>

<p>	
	<%= form_for @class_project do |p| %>

	  <%= p.label :name %>
	  <%= p.text_field :name %>

	  <%= p.label :category %>
	  <%= p.text_field :category %>

	  <%= p.submit %>

	<% end %>
</p>

<p>Do you want to delete <%=@class_project.name %> from your class projects? Click below</p>

<form action = "/class_projects/<%=@class_project.id%>/delete" method = "post">
  <input type = "submit" value = "Delete forever!">
</form>

app/views/class_projects/index.html.erb
<h1>Tony Plaza's Omaha Code School Projects</h1>

<p>These are sure to be amazing!</p>

<% @class_projects.each do |proj|%>
	<!-- <p><%= proj.name%> <%= proj.category%></p> -->
	<p><%= link_to(proj.name, class_project_path(proj.id)) %></p>
<%end%>

<%= link_to("New Class Project", new_class_project_path) %>

app/views/class_projects/new.html.erb
<h1>New Project</h1>

<% @class_project.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
<% end %>

<%= form_for @class_project do |p| %>

  <%= p.label :name %>
  <%= p.text_field :name %>

  <%= p.label :category %>
  <%= p.text_field :category %>

  <%= p.submit %>

<% end %>

app/views/class_projects/show.html.erb
<h1><%= @class_project.name %>'s Details</h1> 
	<p>Category: <%= @class_project.category %></p>

<%= link_to("Edit Class Project", edit_class_project_path) %>
<%= link_to("Delete Project", delete_class_project_path, :method => :delete) %>